.nh
.TH "WIRELOGD" "1" "Apr 2023" "" ""

.SH NAME
.PP
wirelogd - Wirelogd is a logging daemon for WireGuard.


.SH SYNOPSIS
.PP
\fBwirelogd [flags]\fP


.SH DESCRIPTION
.PP
Wirelogd is a logging daemon for WireGuard.


.SH OPTIONS
.PP
\fB-config\fP=""
	path to JSON configuration file

.PP
\fB-debug\fP[=false]
	enable debug logging

.PP
\fB-log-destination\fP=""
	logging destination, could be "stdout", "syslog" or a file path (default "stdout")

.PP
\fB-log-format\fP=""
	logging format, could be "json" or "text" (default "json")

.PP
\fB-help\fP[=false]
	help for wirelogd

.PP
\fB-refresh\fP=0
	refresh interval in seconds

.PP
\fB-timeout\fP=0
	wireguard handshake timeout in seconds
