.nh
.TH "WIRELOGD" "1" "Aug 2022" "" ""

.SH NAME
.PP
wirelogd - Wirelogd is a logging daemon for WireGuard.


.SH SYNOPSIS
.PP
\fBwirelogd [flags]\fP


.SH DESCRIPTION
.PP
Wirelogd is a logging daemon for WireGuard.


.SH OPTIONS
.PP
\fB-c\fP, \fB--config\fP=""
	path to configuration file

.PP
\fB-d\fP, \fB--debug\fP[=false]
	enable debug logging

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for wirelogd

.PP
\fB-r\fP, \fB--refresh\fP=0
	refresh interval in seconds

.PP
\fB-t\fP, \fB--timeout\fP=0
	wireguard handshake timeout in seconds
