# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

builds:
  - env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
    goarch:
      - "amd64"
      - "arm64"

nfpms:
  - package_name: "wirelogd"
    homepage: "https://github.con/nikaro/wirelogd"
    description: "Wirelogd is a logging daemon for WireGuard."
    maintainer: "Nicolas Karolak <nicolas@karolak.fr>"
    license: "GPLv3"
    formats:
      - "deb"
    recommends:
      - "acl"
    contents:
      - src: "contrib/wirelogd.service"
        dst: "/lib/systemd/system/wirelogd.service"
      - src: "contrib/config.json"
        dst: "/etc/wirelogd/config.json"
      - src: "man/wirelogd.1"
        dst: "/usr/share/man/man1/wirelogd.1"
      - src: "LICENSE"
        dst: "/usr/share/licenses/wirelogd/LICENSE"
    scripts:
      postinstall: "contrib/postinstall-deb.sh"
