---
name: CD

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release:
    name: Release
    needs: [ci]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Dry run
        uses: commitizen-tools/commitizen-action@1f11eb222996406681d2bfa1eb3d997eca46557c # 0.21.0
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: _changelog.md
          dry_run: true

      - name: Bump
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: commitizen-tools/commitizen-action@1f11eb222996406681d2bfa1eb3d997eca46557c # 0.21.0
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: _changelog.md

      - name: Setup Go
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod

      - name: Run GoReleaser
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          args: release --clean --release-notes _changelog.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
