name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh repo clone ${{ github.repository }} ${{ github.workspace }} -- --depth=1 --branch "$BRANCH"

      - name: Install tools
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          /home/linuxbrew/.linuxbrew/bin/brew install \
            actionlint \
            check-jsonschema \
            fd \
            go \
            go-task \
            golangci-lint \
            govulncheck \
            jq \
            prettier \
            shellcheck \
            staticcheck \
            shfmt \
            yamlfmt \
            yamllint \

      - name: Lint
        run: task lint --yes

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh repo clone ${{ github.repository }} ${{ github.workspace }} -- --depth=1 --branch "$BRANCH"

      - name: Install tools
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          /home/linuxbrew/.linuxbrew/bin/brew install \
            go \
            go-task \

      - name: Build
        run: task go:build --yes

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh repo clone ${{ github.repository }} ${{ github.workspace }} -- --depth=1 --branch "$BRANCH"

      - name: Install tools
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          /home/linuxbrew/.linuxbrew/bin/brew install \
            go \
            go-task \

      - name: Test
        run: task go:test --yes
